version: "3.9"

services:
  # ==================== DATABASES ====================
  mongodb:
    image: mongo:latest
    # container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    # container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # ==================== BACKEND SERVICES ====================
  user-service:
    build: ./user-service
    # container_name: user_service
    restart: always
    env_file:
      - ./user-service/.env
    expose:
      - "4002"
    # ports:
    #   - "4002:4002"
    depends_on:
      - mongodb
    volumes:
          - ./user-service:/app
          - /app/node_modules
    deploy:
      replicas: 2   # scale user-service
      restart_policy:
       condition: on-failure

  task-service:
    build: ./task-service
    # container_name: task_service
    restart: always
    env_file:
      - ./task-service/.env
    expose:
      - "4001"
    # ports:
    #   - "4001:4001"
    depends_on:
      - postgres
    volumes:
      - ./task-service:/app
      - /app/node_modules
    deploy:
      replicas: 3   # scale task-service
      restart_policy:
        condition: on-failure

  api-gateway:
    build: ./api-gateway
    # container_name: api_gateway
    restart: always
    env_file:
      - ./api-gateway/.env
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - task-service
    volumes:
      - ./api-gateway:/app
      - /app/node_modules

  # ==================== FRONTEND ====================
  frontend:
    build: ./frontend
    # container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000" # vite default
    depends_on:
      - api-gateway
    volumes:
      - ./frontend:/app
      - /app/node_modules
# ==================== VOLUMES ====================
volumes:
  mongo_data:
  postgres_data:
